### ISSUE TITLE
Show list of verified users in Verifier Dashboard

### ISSUE THREAD

**Issue by albertus-andito** [PPIUK/ppi-portal-frontend#21]
**Is your feature request related to a problem? Please describe.**
Sometimes, verifier needs to check whether an account is a duplicate or not (same person with different email address). Thus verifier needs to go to another page and search for the name, which is one click too many. Additionally, there is no interface for the verifier to see the uploaded CAS of a verified user. CAS can only be seen for users that are pending (unverified), flagged, and blocked.

**Describe the solution you'd like**
- Add a table consisting of verified users in the Verified Dashboard
- Consequently, when opening the verified user profile, CAS should be shown.

**Describe alternatives you've considered**
When opening a user profile in any way, CAS could be shown, but only to 'verifier' role.

**Additional context**

**Comment by raka-gunarto** [comment]
I was thinking a split view, and using [https://www.npmjs.com/package/string-similarity](this npm package) to suggest similar profiles with the same name

**Comment by albertus-andito** [comment]
>  using [this npm package](https://www.npmjs.com/package/string-similarity) to suggest similar profiles with the same name

Interesting package, I didn't know that F1 score can be used this way and performs better than edit distance

**Comment by raka-gunarto** [comment]
Anyway, working on this on #22
